Initial commit: Add Nimba SMS API client
nimbasms/nimbasms-node pull request #1
Opened 2023-09-17 19:54 UTC by moustaphaotf

- Implemented the Nimba SMS API client classes (ContactManager, SenderNameManager, etc.).
- Added functionality for handling contacts, sender names, groups, accounts, and messages.
- Integrated the client with the Nimba SMS API endpoints.

Forked from: https://github.com/nimbasms/nimbasms-node
Signed-off-by: Mamadou Moustapha Diallo <moustaphaotf@gmail.com>

2023-09-17 20:00 UTC, moustaphaotf commented
## Titre: Ajouter le client de l'API Nimba SMS

### Aperçu :
Cette PR introduit le client de l'API Nimba SMS, qui fournit un module Node.js pour une communication transparente avec l'API Nimba SMS. Le client comprend des fonctionnalités pour gérer les contacts, les noms d'expéditeur, les groupes, les comptes et les messages.

### Modifications apportées :
- Création d'un module dédié pour le client de l'API Nimba SMS.
- Implémentation des classes du client : `ContactManager`, `SenderNameManager`, `GroupManager`, `AccountManager` et `MessageManager`.
- Ajout de méthodes pour les opérations courantes telles que la création, la liste et la récupération de ressources.
- Intégration d'Axios pour effectuer des requêtes HTTP vers l'API Nimba SMS.
- Configuration de la clé API et des URL de ressources pour une initialisation facile.

### Tests :
J'ai effectué des tests approfondis de la fonctionnalité du client, notamment :
- Création et récupération de contacts, de groupes, de noms d'expéditeur et de comptes.
- Liste des ressources disponibles avec divers paramètres de requête.
- Gestion des exceptions et des réponses d'erreur de manière appropriée.
- Vérification de l'autorisation correcte avec la clé API.

Notes supplémentaires : Veuillez examiner et fournir des commentaires. Ce client permet une interaction efficace avec l'API Nimba SMS et peut être bénéfique pour votre projet. Merci !

2023-09-17 20:37 UTC, hadpro24 commented
> ## Titre: Ajouter le client de l'API Nimba SMS
> ### Aperçu :
> 
> Cette PR introduit le client de l'API Nimba SMS, qui fournit un module Node.js pour une communication transparente avec l'API Nimba SMS. Le client comprend des fonctionnalités pour gérer les contacts, les noms d'expéditeur, les groupes, les comptes et les messages.
> ### Modifications apportées :
> 
>     * Création d'un module dédié pour le client de l'API Nimba SMS.
> 
>     * Implémentation des classes du client : `ContactManager`, `SenderNameManager`, `GroupManager`, `AccountManager` et `MessageManager`.
> 
>     * Ajout de méthodes pour les opérations courantes telles que la création, la liste et la récupération de ressources.
> 
>     * Intégration d'Axios pour effectuer des requêtes HTTP vers l'API Nimba SMS.
> 
>     * Configuration de la clé API et des URL de ressources pour une initialisation facile.
> 
> 
> ### Tests :
> 
> J'ai effectué des tests approfondis de la fonctionnalité du client, notamment :
> 
>     * Création et récupération de contacts, de groupes, de noms d'expéditeur et de comptes.
> 
>     * Liste des ressources disponibles avec divers paramètres de requête.
> 
>     * Gestion des exceptions et des réponses d'erreur de manière appropriée.
> 
>     * Vérification de l'autorisation correcte avec la clé API.
> 
> 
> Notes supplémentaires : Veuillez examiner et fournir des commentaires. Ce client permet une interaction efficace avec l'API Nimba SMS et peut être bénéfique pour votre projet. Merci !

Merci @moustaphaotf je vais faire un review. Tu peux deja ajouter une documentation de l'utilisation du client sur le fichier ReadMe en suivant la meme approche que pour le client `python`. Merci

2023-09-17 20:47 UTC, moustaphaotf commented
@hadpro24 avec plaisir, merci !

2023-09-18 17:26 UTC, hadpro24 requested changes
Bonjour @moustaphaotf Bravo pour le travail, c'est globalement un excellent travail. Je t'ai laisse quelques points a revoir. Une fois corrige, on va merge et deployer le package sur npm. Je pourrais te donner access a mon compte pour que tu puisses le faire. Merci

2023-09-18 17:26 UTC, hadpro24 commented on README.md
> +    API_URL = 'https://api.nimbasms.com/v1',
API_URL doit etre en interne, le client ne devrait pas avoir a le preciser

2023-09-18 17:26 UTC, hadpro24 commented on README.md
> +npm install nimbasms
Est il disponible sur npm package manager ? npmjs.com ?

2023-09-18 17:26 UTC, hadpro24 commented on README.md
> +npm install nimbasms
Sinon il faudra l'ajouter apres le review

2023-09-18 17:26 UTC, hadpro24 commented on README.md
> +    API_KEY = 'XXXX', // Base 64 encoded
Le client devrait pouvoir fournir : le SID et SECRET_KEY. En suite en interne tu vas encoder en base64 ou le passer directement dans le HTTP. Tu peux regarder l'approce du client 'python'
'

2023-09-18 17:26 UTC, hadpro24 commented on README.md
> +    API_KEY = 'XXXX', // Base 64 encoded
La meme chose ici : SID et SECRET_KEY plutot que API_KEY directement

2023-09-18 17:26 UTC, hadpro24 commented on package.json
> +  "name": "nimbasms-node",
Le nom devrait il pas etre 'nimbasms' ? pas besoin de precise 'node'

2023-09-18 17:26 UTC, hadpro24 commented on package.json
> +  "author": "Mamadou Moustapha Diallo",
Le nom de l'auteur doit etre 'Nimba SMS' on va ajouter ton nom dans les contributeurs apres

2023-09-18 17:26 UTC, hadpro24 commented on package.json
> +    "dotenv": "^16.3.1"
"dotenv" est il une dependance du package ou uniquement le besoin pour les tests ?

2023-09-18 17:26 UTC, hadpro24 commented on src/_ressource.js
> +    constructor({API_KEY, RESSOURCE_URL}) {
Tu pourrais peut etre stocker en dure 'Ressource_url' quelques part ici dans le code

2023-09-18 17:26 UTC, hadpro24 commented on src/_ressource.js
> +    constructor({API_KEY, RESSOURCE_URL}) {
ET modifier cette class pour prendre en compte 'SID' et 'secret_key' au lieu de API_KEY

2023-09-18 17:26 UTC, hadpro24 commented on src/messages.js
> +    async list (params) {
Dans cette fonction j'ai pas vu, le procesus de pagination ? L'idee etait de permetre de passer de la page suivant ou precedente, s'il y'a des donnees

2023-09-18 17:26 UTC, hadpro24 commented on src/sendernames.js
> +    list = async (params) => {
La meme chose ici, la pagination

2023-09-18 17:26 UTC, hadpro24 commented on src/groups.js
> +    async list (params) {
Je n'ai pas vu la pagination ?

2023-09-18 22:47 UTC, moustaphaotf commented on README.md
> +npm install nimbasms
Non, pas encore mais un test en local a donné le résultat, c'est pourquoi je l'ai mis comme ça

2023-09-19 12:46 UTC, hadpro24 requested changes
Merci @moustaphaotf pour les changements, je t'ai laisse quelques messages a corrige.

2023-09-19 12:46 UTC, hadpro24 commented on src/client.js
> +    constructor({SERVICE_ID, SECRET_TOKEN}) {
Il faut eviter les repetitions et l'affectation de tous les gestionnaire dans le constructeur. Certains vont l'utiliser juste pour envoyer un message, ils n'ont pas besoin que tous les autres soit instancier et mis en memoire. Il faut utiliser une approche (lazy loading) en creant des methods.

```node
get contactManager() {
        if (!this._contactManager) {
            this._contactManager = new ContactManager({
                SERVICE_ID: this._serviceId,
                SECRET_TOKEN: this._secretToken,
            });
        }
        return this._contactManager;
    }
```
Re : https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get

2023-09-19 12:46 UTC, hadpro24 commented on src/_ressource.js
> +            if(params.limit && (isNaN(params.limit) || params.limit < 0)) {
J'ai l'impression que cette condition, laisse passer une chaine de caractere. Que'est ce que tu penses de le remplacer par ca a la place : 
```node
if (params?.limit !== undefined && (typeof params.limit !== 'number' || params.limit < 0))
```

2023-09-19 12:46 UTC, hadpro24 commented on src/_ressource.js
> +            if(params.offset && (isNaN(params.offset) || params.offset < 0)) {
La meme chose ici

2023-09-19 17:28 UTC, moustaphaotf commented on README.md
> +npm install nimbasms
Un compte sur npmjs ?

2023-09-19 17:30 UTC, moustaphaotf commented on src/_ressource.js
> +            if(params.limit && (isNaN(params.limit) || params.limit < 0)) {
J'ai testé avec la chaîne de caractères, mais il semblait ne pas y avoir de soucis, mais pour plus de robustesse, nous allons faire comme vous suggérez ^

2023-09-19 17:51 UTC, moustaphaotf commented
Je viens de faire une remarque, le fait que j'ai fait remonter quelques méthode comme list au niveau de Ressource level alors les classes qui en héritent comme account ont accès à cette méthode, est-ce bon en soi ou alors mieux vaut que je laisse exposées les méthodes qui servent la ressource concernée elle-même ?

2023-09-19 21:40 UTC, hadpro24 requested changes
Encore quelques modifications et ca devrait etre bon. Merci

2023-09-19 21:40 UTC, hadpro24 commented on src/client.js
> +        if(!this._messagesManager) {
Tu dois declarer cette variable dans le constructeur : `this._messagesManager = null` 
Ainsi que les autres sinon le code ne passera pas

2023-09-19 21:40 UTC, hadpro24 commented on src/client.js
> +        if(!this._groupManager) {
La meme chose

2023-09-19 21:40 UTC, hadpro24 commented on src/client.js
> +        if(!this._senderNameManager) {
La meme chose

2023-09-19 21:40 UTC, hadpro24 commented on src/client.js
> +        if(!this._contactManager) {
La meme chose

2023-09-19 21:40 UTC, hadpro24 commented on src/client.js
> +            this._accountManager = new AccountManager({
La meme chose

2023-09-19 21:41 UTC, hadpro24 commented
> Je viens de faire une remarque, le fait que j'ai fait remonter quelques méthode comme list au niveau de Ressource level alors les classes qui en héritent comme account ont accès à cette méthode, est-ce bon en soi ou alors mieux vaut que je laisse exposées les méthodes qui servent la ressource concernée elle-même ?

Ce n'est pas une mauvaise chose, c'est plutot le contraire. L'heritage est une bonne idee

2023-09-20 07:10 UTC, moustaphaotf commented
J'ai eu quelques soucis de test surtout avec l'envoie des requêtes de vérification:

- Quand j'envoie une requête sans message, le destinataire ne reçoit pas le message malgré la requête est bien prise en compte (car le résultat que je reçois en témoigne, il y a `{verificationid, code, url}` dans la réponse)
- Quand j'envoie une requête avec le message `"Code de vérification <1234>"`, là aussi c'est comme le cas précedent
- Si je twick le message, là ça marche, par exemple `"Votre code: <1234>"` marche bien, de même que `"Code vérification machin <1234>"`.

A part cela, question de curiosité: si j'ai bien compris le principe, tu émet une requête de vérification et tu sauvegardes la réponse `{verificationid, code, url}` dans ta base de données et si il y a une vérification à faire, tu la réutilises ?

2023-09-20 07:13 UTC, moustaphaotf commented
Egalement, au niveau de la requête de récupération des messages, `/GET | https://api.nimbasms.com/v1/messages`, il y a un filtre en place sur les dates, mais la question que j'avais c'est quel doit être leur format ? Ce n'est pas précisé dans la documentation.

2023-09-20 07:14 UTC, moustaphaotf commented
> > Je viens de faire une remarque, le fait que j'ai fait remonter quelques méthode comme list au niveau de Ressource level alors les classes qui en héritent comme account ont accès à cette méthode, est-ce bon en soi ou alors mieux vaut que je laisse exposées les méthodes qui servent la ressource concernée elle-même ?
> 
> Ce n'est pas une mauvaise chose, c'est plutot le contraire. L'heritage est une bonne idee

D'accord, ça marche alors ^

2023-09-20 23:30 UTC, hadpro24 requested changes
@moustaphaotf Corrige ce message. Et ca devrait etre bon

2023-09-20 23:30 UTC, hadpro24 commented on src/verifications.js
> +            console.log({to, message, sender_name, expiry_time, attempts, code_length})
Il faut retirer les `console.log`

2023-09-20 23:34 UTC, hadpro24 commented
> Egalement, au niveau de la requête de récupération des messages, `/GET | https://api.nimbasms.com/v1/messages`, il y a un filtre en place sur les dates, mais la question que j'avais c'est quel doit être leur format ? Ce n'est pas précisé dans la documentation.

Je vais verifier. Tu pourras faire un commit pour ce point apres

2023-09-21 11:07 UTC, moustaphaotf commented
J'ai effectué le dernier changement, vérifiez également au niveau de l'envoi de la requête de vérification, je pense qu'il y a un soucis là-bas en fonction du message reçu qui empêche l'envoi du SMS chez le destinataire.

2023-09-21 13:42 UTC, hadpro24 requested changes
Hello @moustaphaotf quelques optims a revoir.

2023-09-21 13:42 UTC, hadpro24 commented on src/_ressource.js
> +    async list(params){
Qu'est ce que tu penses de remplacer ce code par ceci :


```js
async list(params) {
    if (params !== undefined) {
        if (typeof params !== 'object') {
            throw new Error("Query parameters must be an object");
        }

        const { limit, offset } = params;

        if (limit !== undefined && (typeof limit !== 'number' || limit <= 0)) {
            throw new Error("limit query parameter must be a positive number");
        }

        if (offset !== undefined && (typeof offset !== 'number' || offset < 0)) {
            throw new Error("offset query parameter must be a non-negative number");
        }
    }

    const { next, count, previous, ...restData } = await this.request({
        url: this.RESSOURCE_URL,
        params: params,
    });

    this._next = next;
    this._count = count;
    this._previous = previous;

    return restData;
}

```

2023-09-21 13:43 UTC, hadpro24 commented
> J'ai effectué le dernier changement, vérifiez également au niveau de l'envoi de la requête de vérification, je pense qu'il y a un soucis là-bas en fonction du message reçu qui empêche l'envoi du SMS chez le destinataire.

Pour ce probleme, j'ai teste de mon cote. je ne l'ai pas rencontre. Tu peux reverifier stp. Si ca persist, tu me dis

2023-09-21 23:30 UTC, moustaphaotf commented
En passant, grâce à l'héritage, je n'ai modifié qu'un seul emplacement, très pratique.
Merci pour le recadrement ^_^

2023-09-22 02:28 UTC, hadpro24 approved these changes
Work Done. Thank you @moustaphaotf

2023-09-22 02:29 UTC, merged

2023-09-22 02:35 UTC, moustaphaotf commented
Vous vous chargez de publier le module sur npmjs ?

On Fri, Sep 22, 2023, 2:29 AM Harouna Diallo ***@***.***>
wrote:

> Merged #1 <https://github.com/nimbasms/nimbasms-node/pull/1> into main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nimbasms/nimbasms-node/pull/1#event-10442435555>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVXEXAPTCVE3OIOBXTOAROTX3TZYNANCNFSM6AAAAAA432GKMI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-09-23 00:11 UTC, hadpro24 commented
Oui. Je viens de m'apercevoir qu'on a ajouté un package-lock.json dans le repo. Il faut l'ajouter dans le gitignore et envoyer un autre pull request